### ISSUE TITLE
Kindly provide access to com.arthenica:mobile-ffmpeg

### ISSUE THREAD

**Issue by oluwabajio** [lincollincol/AudioTool#2]
Hello,

Thanks for this wonderful library which i am using in one of my apps and it works perfectly.

Currently, i would love to do some other tasks with ffmpeg and i see that your library already imports this library. com.arthenica:mobile-ffmpeg.

How do i have access to com.arthenica:mobile-ffmpeg as i ndont want to import it again to prevent my apkk size from becoming too big.

i tried this, import com.arthenica.mobileffmpeg.FFmpeg, it doesnt work

**Comment by lincollincol** [comment]
Hello @oluwabajio , you can use `executeFFprobe(String command)` and `executeFFmpeg(String command)` to run your own command.

**Comment by oluwabajio** [comment]
Thank you so much for this, it works.

**Comment by oluwabajio** [comment]
Hello, Also i want to ask.

Does executeFFmpeg(String command) provide callback to notify me when ffmpeg has finished executing the command

**Comment by lincollincol** [comment]
@oluwabajio No, currently this method doesn't provide a callback but your idea sounds good. I'll add this feature tomorrow!

**Comment by oluwabajio** [comment]
Ok, thanks. I look forward to that.

**Comment by lincollincol** [comment]
Hello @oluwabajio , now you can get full access to ffmpeg functional with new AudioTool version 1.2. You should also add ffmpeg dependency to your project `implementation 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS'`
